name: firebase_oa
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  
  #State Management
  get: ^4.6.6

  #Internet Connection
  connectivity_plus: ^5.0.2

  #Graph
  fl_chart: ^0.68.0
  
  #Screen Time
  wakelock: ^0.6.2

  #Pose Detection
  camera: ^0.10.5+9
  google_mlkit_pose_detection: ^0.12.0
  google_mlkit_commons: ^0.7.1
  audioplayers: ^6.0.0
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/placeholders/
    - assets/sounds/correct_sound_effect.mp3

 